```{r}
library("ISLR") 
library("tidyverse") 
library("ggplot2")
```


First, read the dataset and clean it
```{r}
# this will have problems
d = read_delim("./title_basics.tsv")

# so we drop incomplete rows to make it not
d = drop_na(d, genres)
```
```{r echo=False}
# this should not have problems
ratings = read_tsv("./title_ratings.tsv")
```
```{r}
crew = read_tsv("./title_crew.tsv")
```

here for testing purposes
```{r}
problems(ratings)
```

Merging Data
```{r}
data = list(d, ratings, crew)

data = reduce(data, inner_join, by = 'tconst')
```


===Start on descriptive data analysis===
First, we find out the average rating for a movie over all time
```{r}
# histogram of ratings
ggplot(ratings, aes(x=averageRating)) + geom_histogram(fill="white", color="black") + scale_x_continuous(name="rating", breaks=seq(0, 10, 1))
  
```
As we can see, most common ratings are about 7.5
==Now try plotting rating vs release year using a scatterplot==
```{r}

```
Include "questions" we asked




Predictive data analysis w/ linear regression model
```{r}

```